language: python

sudo: required
services:
  - docker

branches:
  only:
    - master
    - v0.2
    - /^v\d+\.\d+\.\d+$/

python:
    - 3.3
    - 3.4
    - 3.6
env:
    matrix:
        - KAFKA_VERSION=0.9.0.1 SCALA_VERSION=2.11 PYTHONASYNCIODEBUG=1
        - KAFKA_VERSION=0.9.0.1 SCALA_VERSION=2.11 PYTHONASYNCIODEBUG=1 AIOKAFKA_NO_EXTENSIONS=1
        - KAFKA_VERSION=0.10.2.1 SCALA_VERSION=2.11 PYTHONASYNCIODEBUG=1
        - KAFKA_VERSION=0.10.2.1 SCALA_VERSION=2.11 PYTHONASYNCIODEBUG=1 AIOKAFKA_NO_EXTENSIONS=1
        - KAFKA_VERSION=0.11.0.0 SCALA_VERSION=2.12 PYTHONASYNCIODEBUG=1
        - KAFKA_VERSION=0.11.0.0 SCALA_VERSION=2.12 PYTHONASYNCIODEBUG=1 AIOKAFKA_NO_EXTENSIONS=1

before_install:
    - sudo apt-get update
    - sudo apt-get install -y libsnappy-dev

install:
    - pip install --upgrade pip setuptools wheel
    - pip install flake8
    - pip install "pytest<3.3.0" pytest-cov pytest-catchlog docker-py
    - pip install codecov
    - pip install cython
    - pip install python-snappy
    - pip install lz4 xxhash
    - pip install pathlib
    - pip install -vv -Ue .

script:
  - make cov FLAGS="-v"

after_success:
  - codecov

deploy:
  provider: pypi
  user: andrew.svetlov
  password:
    secure: "PyOEy+tshUMOIKJ8TJfSPNuS1yjwpl5iiEO8Iwi1jwBiOhI5aumpHWWeWed/JvyAFRXq+m3vn0WKtK+KzN8rDhSVOfRHONQmCpD9cJ+KMRNA2sOom17CH2n37f3VuiwhjZWXTM4rVE5QTq+5JZVQ02aSdpcaGaIUNtj6T2wahzg="
  distributions: "sdist"
  on:
    tags: true
    all_branches: true
    python: 3.6
