version: "= 0"

language: python

branches:
  only:
  - master
  - v0.2
  - "/^v\\d+\\.\\d+\\.\\d+$/"
  - "/^v\\d+\\.\\d+\\.\\d+\\.dev\\d*$/"

stages:
- &stage_sanity_test Unit tests on container workers
- &stage_functional Run main functional tests
- name: &stage_deploy Optionally run deploy
  # This will prevent deploy unless it's a tagged commit:
  if: tag IS present

matrix:
  include:
    - stage: *stage_sanity_test
      sudo: false
      python: 3.6
      script:
      - make ci-test-unit

    - stage: *stage_functional
      sudo: required
      python: 3.6
      services:
      - docker
      env: KAFKA_VERSION=0.11.0.0 SCALA_VERSION=2.12 PYTHONASYNCIODEBUG=1
      script:
      - make ci-test-all

    - stage: *stage_deploy
      python: 3.6
      script: skip
      deploy:
        provider: pypi
        user: aio-libs-bot
        password:
          secure: BSV2mPhyeyM8N7IdNtAlF11+pAQu9jdJQUOWWSfQBar+qgfFobkm23OZtvVZzl68U+cYzROlv6m66Xu9SN5MdPezrEXKKmcnzC/iREzHyB//Edrj+WsyqbmeqW3MGNgUu3bGq23Jw629jU3oGCm59cCa04Z/ZLhWHowH0UVVI/cbzfI5nc0nJkPSzYE2+L5DUjLGUgAA2+bygAWu2DpaUlVq5Pd+ApRSwvhg+qV2QHYCM6ypX5X0IjVNORQev9UuiKgAEFAeYcCgi0LB1DuasRVCf+yQeHa7xUGjtGS4PNWyK1jyyvJGYjV9XI1vUfnR5iKzKQVkBafqcCsW65H4D7m9cSVfU9P23XaHmwKAqYHG0LOyis/NT4cI5lRu7NhyTb6k3qex5jOGlIWrGGuA2Aer8jsMZ4msZDYlRksBUQD4TJpeoCxYikxuPx9ylE8cGle2qMHzdayM31rZ6AJSqZEMGFlWPIOsvTyBtO0yYFF+glP/cw1FUxDYTeBynEyjIH0PpMGwLY8rU4EZlQI4pU0aKEsziZt6AkkkGE7R3KMTWiOcqdprNp41RoW1Bqjrkf/j0iIzsvZv0aol0hfcfxg3jKnGagVZfmX9K3UQexDgIe5n/1P/dM91Zh3uMkrRMt2WYExd6nI5B3YzxTj1xzla7fYFixl6BudS9lhkmvg=
        distributions: sdist
        on:
          tags: true
          all_branches: true
          python: 3.6

python:
- 3.6

before_install:
- sudo apt-get update
- sudo apt-get install -y libsnappy-dev

install:
- pip install --upgrade pip setuptools wheel
- pip install flake8
- pip install "pytest<3.3.0" pytest-cov pytest-catchlog docker-py
- pip install codecov
- pip install cython
- pip install python-snappy
- pip install lz4 xxhash
- pip install pathlib
- pip install -vv -Ue .

after_success:
- codecov
